### ISSUE TITLE
Bedtools intersect error

### ISSUE THREAD

**Issue by ssamberkar** [Ensembl/plant-scripts#2]
Hi Bruno,

I had an error when trying out your pangenes script. 
Apparently, the minimap step completed but the bedtools intersection failed.
Here's the log from the run.

`
work/annotation_comparisons/Asian_rice_pangenome_annotations/plant-scripts/pangenes/get_collinear_genes.pl -sp1 orynnotations/fasta/dna/Ketan.Nangka.VYIC01.1.fa -gf1 work/annotation_comparisons/Asian_rice_pangenome_annotations/gff/pativa_cm -fa2 work/annotation_comparisons/Asian_rice_pangenome_annotations/fasta/dna/Chao.Meo.VYIH01.1.fa -gf2 work/aoding/oryza_sativa_chao_meo_core_4_87_1.gff -out test_ketan_natel_mm2_homologies.tsv -a 0 -ovl 0.5 -q 50 -wf 0 -c 0 -

mapping parameters:
$MINIMAPPARS: --secondary=no --cs -x asm20

 36612 genes parsed in work/annotation_comparisons/Asian_rice_pangenome_annotations/gff/protein-coding/oryza_sativa_
 36999 genes parsed in work/annotation_comparisons/Asian_rice_pangenome_annotations/gff/protein-coding/oryza_sativa_
 computing pairwise genome alignment with minimap2

[M::mm_idx_gen::8.531*1.58] collected minimizers
[M::mm_idx_gen::9.443*2.19] sorted minimizers
[M::main::11.467*1.98] loaded/built the index for 34 target sequence(s)
[M::mm_idx_stat] kmer size: 19; skip: 10; is_hpc: 0; #seq: 34
[M::mm_idx_stat::11.786*1.95] distinct minimizers: 48898389 (91.20% are singletons); average occurrences: 1.427; aver
[M::main] Version: 2.22-r1101
[M::main] CMD: minimap2 -x asm20 -t 8 -d _oryza_sativa_kn.mmi work/annotation_comparisons/Asian_rice_pangenome_annota
[M::main] Real time: 21.972 sec; CPU: 23.227 sec; Peak RSS: 2.841 GB
[M::main::10.113*0.27] loaded/built the index for 34 target sequence(s)
[M::mm_mapopt_update::10.621*0.30] mid_occ = 192
[M::mm_idx_stat] kmer size: 19; skip: 10; is_hpc: 0; #seq: 34
[M::mm_idx_stat::10.938*0.32] distinct minimizers: 48898389 (91.20% are singletons); average occurrences: 1.427; aver
[M::worker_pipeline::261.964*7.25] mapped 124 sequences
[M::main] Version: 2.22-r1101
[M::main] CMD: minimap2 --secondary=no --cs -x asm20 -t 8 -o _oryza_sativa_cm.oryza_sativa_kn.minimap2.paf _oryza_satons/fasta/dna/Chao.Meo.VYIH01.1.fa
[M::main] Real time: 261.984 sec; CPU: 1899.110 sec; Peak RSS: 16.535 GB
 minimap2 finished

 ERROR: failed generating _oryza_sativa_cm.gene.oryza_sativa_kn.minimap2.intersect.overlap0.5.bed file (bedtools)
`

**Comment by eead-csic-compbio** [comment]
HI @ssamberkar , will have a look probably tomorrow, it would help if I can use exactly the same files you are using, can you please share them?
Bruno

**Comment by ssamberkar** [comment]
Sure,

The fasta files are here:
1. [Ketan.Nangka](https://drive.google.com/file/d/1oXDZzswEpZThs2IPtPwxUlT-WRj95PqQ/view?usp=sharing)
2. [Chao.Meo](https://drive.google.com/file/d/1FfgrD731_PA-lXrJX8cRcP8NJU9_j2Nv/view?usp=sharing)

The gff files are here:
1. [Ketan.Nangka](https://drive.google.com/file/d/1zqpuKL6uSNS3EoMWvsTf2DfdkaFcYv22/view?usp=sharing)
2. [Chao.Meo](https://drive.google.com/file/d/1bbpw7ETeQl7cbQ4VOpkHZEH51HlK2duq/view?usp=sharing)

**Comment by eead-csic-compbio** [comment]
I'll have a look today, probably AFTER the meeting :-(

**Comment by eead-csic-compbio** [comment]
HI @ssamberkar , it seems the FASTA files you sent me contain protein sequences, I would need genomic nucleotide sequences, as that's what minimap2 will align first,
Bruno
