### ISSUE TITLE
wfmash

### ISSUE THREAD

**Issue by ChenSh1ne** [Ensembl/plant-scripts#3]
Hi,
 I tested your pangene pipeline and it works fine with 'minimap2' but not work with 'wfmash' software , the error message is reported below. I also found that minimap2's multithreading didn't work when comparing large genomes.

[wfmash::align] Alignment output file = /dev/stdout
[wfmash::align] time spent read the reference sequences: 5.07e-07 sec
[wfmash::align::computeAlignments] aligned 100.00% @ 7.38e+05 bp/s elapsed: 00:00:02:17 remain: 00:00:00:00
[wfmash::align::computeAlignments] count of mapped reads = 142, total aligned bp = 101227202
[wfmash::align] time spent computing the alignment: 1.37e+02 sec
[wfmash::align] alignment results saved in: /dev/stdout
# ERROR: failed generating /share/home/software/plant-scripts/pangenes/AT_pangenes/tmp/_Eri.C24.wfmash.split.all.paf file (/share/home/software/plant-scripts/pangenes/bin/wfmash/build/bin/wfmash -p 95 -s 3000 -t 4 /share/home/software/plant-scripts/pangenes/AT_pangenes/_C24.fna /share/home/software/plant-scripts/pangenes/AT_pangenes/_Eri.fna > /share/software/plant-scripts/pangenes/AT_pangenes/tmp/_Eri.C24.wfmash.split.all.paf)
# EXIT: failed while doing genome alignment (/share/home/stu_chenshuai/software/plant-scripts/pangenes/_collinear_genes.pl -ovl 0.5 -t 4 -sp1 C24 -fa1 /share/home/software/plant-scripts/pangenes/AT_pangenes/_C24.fna -gf1 /share/home/software/plant-scripts/pangenes/AT_pangenes/_C24.gff -sp2 Eri -fa2 /share/home/software/plant-scripts/pangenes/AT_pangenes/_Eri.fna -gf2 /share/home/software/plant-scripts/pangenes/AT_pangenes/_Eri.gff -B bedtools -T /share/home/software/plant-scripts/pangenes/AT_pangenes/tmp/ -add -out /share/home/software/plant-scripts/pangenes/AT_pangenes/_C24.Eri.algWmsh.overlap0.5.tsv -r -wf -W /share/home/software/plant-scripts/pangenes/bin/wfmash/build/bin/wfmash  > /dev/null)

Regards,

Chen

**Comment by brunocontrerasmoreira** [comment]
Thanks for testing it @ChenSh1ne , I am doing some tests but the latest wfmash binary is failing in the indexing step, even earlier. Will see if it works with a previous version

**Comment by brunocontrerasmoreira** [comment]
For large genomes I would use option -s which splits the genome/index in individual chromosomes

**Comment by ChenSh1ne** [comment]
>
I have used option '-s', but minimap2's multithreading not working  well and it stills cosuming mang times. so I decide use wfmash.
Hope this problem will be solved as soon as possible!

**Comment by ChenSh1ne** [comment]
> I have used option '-s', but minimap2's multithreading not working  well and it stills cosuming mang times. so I decide use wfmash.
Hope this problem will be solved as soon as possible!

**Comment by brunocontrerasmoreira** [comment]
@ChenSh1ne mapping with wfmash (-w) requires make install_wfmash and seems to work now after a few fixes. Please git pull and try:

    perl get_pangenes.pl -d ../files/test_rice -w -m cluster

    ...
    # number of clusters = 10699 (core = 1406)
    ...

Let me know how that goes,
Bruno

**Comment by ChenSh1ne** [comment]
> 

Thanks, It works now!

Regards,

Chens
