### ISSUE TITLE
May I use repbase database instead of nrTEplants library?

### ISSUE THREAD

**Issue by xiekunwhy** [Ensembl/plant-scripts#4]
Hi,

May I use repbase database instead of nrTEplants library when do repeat masking using this pipeline(https://github.com/Ensembl/plant-scripts/tree/master/repeats)? And why?

Best,
Kun

**Comment by brunocontrerasmoreira** [comment]
Hi @xiekunwhy , yes you can, particularly if you expect your version of RepBase to work well with your species of interest. In the [documentation](https://github.com/Ensembl/plant-scripts/tree/master/repeats#annotation-summary) you'll see a couple of examples of valid FASTA headers:

    >TEdenovo-B-R2315-Map11:repetDB.Mar2020#TIR @Brassica_rapa [S:]
    >AT1TE94285:TAIR10_TE#DNA/MuDR @Arabidopsis_thaliana [S:]

Please let us know if you encounter format issues,
Bruno

**Comment by xiekunwhy** [comment]
Thank for your reply, and I am trying now.

Do you familiar with animal genome, and do you think this pipeline is suitable for animal genome repeat annotation?

Best,
Kun

**Comment by brunocontrerasmoreira** [comment]
Hi @xiekunwhy , I have never tried it with animals, but the original Red paper (see https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-015-0654-5) did. Please read it and decide for yourself. I will only add that this pipeline was designed to make sure all repeats were masked, even if they belonged to unknown families of TEs. The focus was not the annotation. While you can annotate the masked segments of the genome with an external FASTA file, as you are testing right now, no effort is made to makse sure that TEs are masking in one pice, so they can be fragment. Hope this helps,
Bruno
