### ISSUE TITLE
install without sudo privileges

### ISSUE THREAD

**Issue by ericgonzalezs** [Ensembl/plant-scripts#5]
Hi,

I wonder if there is a way to install your scripts without Sudo privileges. 

Thanks,

Eric

**Comment by brunocontrerasmoreira** [comment]
Hi @ericgonzalezs , 
the recipes in the [Makefile](https://github.com/Ensembl/plant-scripts/blob/master/Makefile) should work on Debian/Ubuntu, as that's the platform where these recipes are automatically tested. Currently the following tasks require sudo:

    -sudo apt install -y wget mysql-client libmysqlclient-dev bedtools pip cpanminus
    -sudo apt install cmake libjemalloc-dev zlib1g-dev libgsl-dev libhts-dev
 
The second line are dependencies required to compile wfmash, but those in the first line are general, I guess you are asking about these? 

I guess my response would be to:
* Translate these recipes to your particular OS. There are some examples in the documentation but we can expand them following your experience. I can confirm the dependencies can be installed in Redhat as well, but you might need help from your sysadmin. 
* Find out which scripts you want to use, as the list of dependencies might shrink.

I guess we also think about a bioconda recipe @gnaamati ? That will need discussion at Ensembl and a some work,
Bruno
