### ISSUE TITLE
How to find more information on a repeat in the DB?

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [Ensembl/plant-scripts#6]
Hi,

I have for example, this annotated repeat in a genome:
denovoPeach-B-G4881-Map14:repetDB.Mar2020#Unclassified
From nrTEplantsJune2020.fna
How can I find out more information on the repeat, where it came from etc.?
Thanks,
Theo

**Comment by brunocontrerasmoreira** [comment]
Hi @theo-allnutt-bioinformatics ,

you can find documentation on how the nrTEplants library was compiled at https://github.com/Ensembl/plant_tools/tree/master/bench/repeat_libs

That includes:
* a [table ](https://github.com/Ensembl/plant_tools/tree/master/bench/repeat_libs#11-te-libraries) with the TE libraries used as input for clustering
* a [log file](https://raw.githubusercontent.com/Ensembl/plant_tools/master/bench/repeat_libs/log.M) of the clustering job

Your example seems to be an unclassified peach sequence annotated called at [REPETDB](https://urgi.versailles.inra.fr/Data/Transposable-elements/REPETDB). This is how it looked like in the original file obtained from the source library:

    >noCat_denovoPeach-B-G4881-Map14 -
    caaggcaaggcatgccaacgcaagacaagccaaggcaagacatgccaaggcaaggcatcc
    caaaaatccaatagactcacttactggaaatgccttgaattgtgcaatgacaattccaat
    aaaaggcaaggcatttcaaggacaaggcatgccaaagccaattctgtcgacatttgtggc
    caacgctgtgcaaggcatatgtgggcatgccaacgggcaaggcaatgccaaggcatgcgc
    aaggcaatgccatgccaagcttccaatagcctcactttctcgaaatgccttgaatgggga
    gcaatgccaaggccaagccaaggcaaggcatgccaaggcacgaaatgccaaggccaaggc
    ...

Does this help?
Bruno

**Comment by theo-allnutt-bioinformatics** [comment]
Thanks, that does help, although the repeat was used in peach mapping, it did not originate there and may remain obscure.

Theo

**Comment by theo-allnutt-bioinformatics** [comment]
Could you please describe how you obtained the above sequence? I have tried the REPDB search but it finds nothing for any of the terms in the repeat name. Thanks.

**Comment by theo-allnutt-bioinformatics** [comment]
Also - I cannot find any similarity between this REPETDB repeat and the one annotated in my genome by AnnotRedRepeats.py. See annotated sequence attached.
[peach.fasta.txt](https://github.com/Ensembl/plant-scripts/files/10624852/peach.fasta.txt)

**Comment by brunocontrerasmoreira** [comment]
> Could you please describe how you obtained the above sequence? I have tried the REPDB search but it finds nothing for any of the terms in the repeat name. Thanks.

What I did in 2020 was going to  https://urgi.versailles.inrae.fr/repetdb/begin.do and exported all TE sequences from taxon 'Viridiplantae'. I tried again today and can see that sequence there

**Comment by brunocontrerasmoreira** [comment]
> Also - I cannot find any similarity between this REPETDB repeat and the one annotated in my genome by AnnotRedRepeats.py. See annotated sequence attached. [peach.fasta.txt](https://github.com/Ensembl/plant-scripts/files/10624852/peach.fasta.txt)

Thanks for sharing your sequence. I blasted it against the [peach TE sequence](https://urgi.versailles.inrae.fr/repetdb/report.do?id=88008953) and got significant alignments:

    ~/soft/ncbi-blast-2.6.0+/bin/blastn -query peach.fasta.txt -subject denovoPeach-B-G4881-Map14 -outfmt 6
    peach	denovoPeach-B-G4881-Map14	93.161	3802	207	41	12133	15909	12806	16579	0.0	5531
    peach	denovoPeach-B-G4881-Map14	92.654	3825	205	47	12133	15909	1843	5639	0.0	5437
    peach	denovoPeach-B-G4881-Map14	96.839	1835	57	1	16126	17960	5852	7685	0.0	3066
    peach	denovoPeach-B-G4881-Map14	96.839	1835	57	1	16126	17960	16792	18625	0.0	306

**Comment by theo-allnutt-bioinformatics** [comment]
Hi,

thanks. Not sure why my blast did not work. The [peach TE sequence](https://urgi.versailles.inrae.fr/repetdb/report.do?id=88008953) information is very useful.

Theo
